spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportDesk
    username: root
    password: Yash@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8082